// <auto-generated/>
using System.Runtime.CompilerServices;

// ReSharper disable once CheckNamespace
namespace Cake.Tfx
{
    /// <summary>
    /// This namespace contains Tfx aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension
{
    /// <summary>
    /// This namespace contains members related to Tfx Extension.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Create
{
    /// <summary>
    /// This namespace contains members related to the Tfx Extension Create method.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Install
{
    /// <summary>
    /// This namespace contains members related to the Tfx Extension Install method.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Publish
{
    /// <summary>
    /// This namespace contains members related to the Tfx Extension Publish method.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Share
{
    /// <summary>
    /// This namespace contains members related to the Tfx Extension Share method.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}