// <auto-generated/>
using System.Runtime.CompilerServices;

// ReSharper disable once CheckNamespace
namespace Cake.Tfx
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Create
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Install
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Publish
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Tfx.Extension.Share
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}